### ISSUE TITLE
Phone View - Footer get cut off

### ISSUE THREAD

**Issue by willtnobles** [henryjr1/deeplyrooted_msu#58]

**Comment by henryjr1** [comment]
David and I were confused on where exactly the footer is getting cut off at. On our machines everything seems to scale normally. If you can recreate the issue can you post an image of the problem. (Should be able to just copy and past it into a comment)

**Comment by teriannaj** [comment]
Okay, I can do this.

**Comment by teriannaj** [comment]
![footer floating](https://user-images.githubusercontent.com/26263778/37658748-3e8d40e4-2c1c-11e8-97ef-1c8212ba18e0.PNG)

For me the footer isn't getting cut off but it seems to constantly float in the middle.

**Comment by teriannaj** [comment]
![iphone 8 footer floating](https://user-images.githubusercontent.com/26263778/37658992-d1134b20-2c1c-11e8-9423-55c499d6365c.PNG)

**Comment by slg427** [comment]
Hey, so sorry for not responding sooner. But what Terri sent is the same
thing that I was seeing.
